local settings = require "example.scripts.lib.settings_imgui"
local water = require("water.water")

go.property("time_speed", 0.2)
go.property("is_day", true)

local function set_day()
	water.set_shallow_color(75 / 255, 160 / 255, 195 / 255)
	water.set_deep_color(88 / 255, 160 / 255, 200 / 255)
	water.set_far_color(45 / 255, 75 / 255, 120 / 255)
	water.set_wave1(1.5, 0.2, 20, 3.5)
	water.set_wave2(1.75, 0.2, 25, 1.5)
	water.set_wave_normal_params(20.0, 0.5)

	water.set_foam_params(10, 1.0, 0.5, 1.0)
	water.set_edge_foam_params(0.3, 0.30, 0.1, 0.65)
	water.set_density_params(0.02, 0.3)

	water.set_sparkle_params(30, 0.3, 10000.0, 1.0)
	water.set_lod_params(80, 90)

	go.set("/terrain#model", "ambient_light", vmath.vector4(
		(113 / 255) ^ 2.2,
		(94 / 255) ^ 2.2,
		(27 / 255) ^ 2.2,
		1.0
	))
end

local function set_sunset()
	water.set_shallow_color(200 / 255, 128 / 255, 44 / 255)
	water.set_deep_color(85 / 255, 175 / 255, 200 / 255)
	water.set_far_color(190 / 255, 100 / 255, 135 / 255)
	water.set_wave1(1.5, 0.2, 20, 3.5)
	water.set_wave2(1.60, 0.8, 15, 1.8)
	water.set_wave_normal_params(10.0, 0.5)

	water.set_foam_params(10, 1.0, 0.5, 1.0)
	water.set_edge_foam_params(0.3, 0.30, 0.1, 0.65)
	water.set_density_params(0.02, 0.3)

	water.set_sparkle_params(30, 0.3, 10000.0, 1.0)
	water.set_lod_params(80, 90)
	water.set_sun_color(225 / 255, 100 / 255, 50 / 255)
	water.set_sparkle_color(110 / 255, 100 / 255, 35 / 255)
	water.set_edge_foam_color(245 / 255, 210 / 255, 115 / 255)

	go.set("/terrain#model", "ambient_light", vmath.vector4(
		(116 / 255) ^ 2.2,
		(52 / 255) ^ 2.2,
		(94 / 255) ^ 2.2,
		1.0
	))
end

function init(self)
	msg.post(".", "acquire_input_focus")

	--profiler.enable_ui(true)
	--profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)

	if self.is_day then
		set_day()
	else
		set_sunset()
	end

	water.init(msg.url("/camera"), msg.url("/camera#camera"), msg.url("/sun"), msg.url("/water_surface"), self.time_speed)

	settings.init()
end

function update(self, dt)
	water.update_camera()
	water.update(dt)

	settings.update()
end
